### PR TITLE
fxmanifest

### PR DESCRIPTION
**Pull request by Tinky124**

### CODE REVIEW

**Comment by propstg** [comment]
Hey, thanks. I assume this is a new resource manifest style?

**Comment by Tinky124** [comment]
@propstg yes now its fxmanifest.lua lastest manifest version you can look at es_extended and others script using that!

**Comment by propstg** [comment]
Ah, cool. Thank you!

**Comment by propstg** [comment]
Interesting.

The resource started for me, with this change. But, when I tried to test your other PR, the server-side script seemingly wasn't running at all. Not even a `print ('hello?')` and refresh/restart would work.

Upgrading my server to the latest version fixed it. I was using a version from Oct 2018, lol. The command line autocomplete on the newer version is pretty cool, so thanks for dragging me into 2020 :P

**Pull request merged**
